version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-brave-stable_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/brave:stable@sha256:ea1d1daf4e2fb5b14a7a56f4434dcc8e32fe6a39cc1d2ee2ca7c2859b541610e
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"