version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-fedora-kde_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/webtop:fedora-kde@sha256:92edc1510944bf52a174aa1ae5705796951c1478795de3e48d55f7cfc1a0f4b1
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"