version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-fedora-kde_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/webtop:fedora-kde@sha256:25b4505d08c501121363b4c28c0529a15a3cf41acf7626d30c86286e664e611c
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"