version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-fedora-kde_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/webtop:fedora-kde@sha256:1677b664b70533680ecf78ef7dbb5f4dec9bc4f2d79303333f2300249f0e29b6
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"