version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-firefox_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/firefox:133.0.3@sha256:sha256:2832f198d6a69ee82413b8746660cb2ff6ab57ee0018462a35a939e5f2569bd2
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"