version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-firefox_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/firefox:138.0@sha256:ed94f913a90ec56f6d83e51be40814ecb1f3a74878c157e259febddcf9a37b32
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"