version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-firefox_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/firefox:135.0.1@sha256:75f98188397988d78a36390c45844c1ed18b92480237666cd317ab7a06db9d67
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"