version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-brave_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/brave:1.74.51@sha256:55f75a2f73b68ffe46018cec9ce8bfb69e3880b03bdee7c4d7c82ee9916b7125
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"