version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-brave_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/brave:1.77.101@sha256:c22a1e9c60a9a043a8ccda5f40b6a6966029e7009d70cc9277739368f861f4ca
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"