version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-kubuntu_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/webtop:kubuntu@sha256:f6437beb3079341a23e4987b2e3aa668d32720d0cf3e6a678b749c7712f4b09b
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"