version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-kubuntu_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/webtop:kubuntu@sha256:eac92b345bf37ec493b74625a19426cb239b6c2dcf93f199aa43db14842c30e7
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"