version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-qbittorrent_1
      APP_PORT: 8090

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8090
      - TORRENTING_PORT=35114
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 35114:35114
      - 35114:35114/udp
    restart: unless-stopped
