version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-qbittorrent_server_1
      APP_PORT: 8096

  server:
    image: lscr.io/linuxserver/qbittorrent:5.0.4@sha256:81a71641d2ee65fbecfabf3388f0d6b7b053e7266658b1fb7efee8900d06f010
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8096
      - TORRENTING_PORT=35114
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 35114:35114
      - 35114:35114/udp
    restart: unless-stopped
