version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-zorinos-core_server_1
      APP_PORT: 3588

  server:
    image: ghcr.io/tibor309/webtop:zorinos-core@sha256:1ae049541614f5b5b1fb023de7dfe479953b0492356aae42cda4794346b1882d
    security_opt:
      - seccomp:unconfined
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"