version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-zen_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/zen:1.7.4b@sha256:536fc181e0870f5a3b00a4104f29c32b494ba12b5bf2836f242c831a09c5e8c7
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"